# Base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy requirements and app files
COPY requirements-frontend.txt .
COPY chatbot.py .

# Install dependencies
RUN pip install --no-cache-dir -r requirements-frontend.txt

# Expose the default Streamlit port
EXPOSE 8501

# Run Streamlit app
CMD ["streamlit", "run", "chatbot.py"]