name: Docker Compose Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Log in to DockerHub (optional)
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Backend Image
    - name: Build Backend
      run: |
        docker-compose build backend

    # Build Frontend Image
    - name: Build Frontend
      run: |
        docker-compose build frontend

    # Test Backend Image for Vulnerabilities
    - name: Scan Backend Image for Vulnerabilities
      uses: aquasecurity/trivy-action@v0.11.0
      with:
        image-ref: backend:latest

    # Test Frontend Image for Vulnerabilities
    - name: Scan Frontend Image for Vulnerabilities
      uses: aquasecurity/trivy-action@v0.11.0
      with:
        image-ref: frontend:latest

    # Run the containers
    - name: Run Docker Compose
      run: |
        docker-compose up --detach --abort-on-container-exit

    # Verify Backend
    - name: Test Backend Connectivity
      run: |
        curl http://localhost:8000/chat || echo "Backend not reachable"

    # Verify Frontend
    - name: Test Frontend Connectivity
      run: |
        curl http://localhost:8501 || echo "Frontend not reachable"
